---
- name: Install and configure web server
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove default Apache page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy custom website files
      copy:
        src: ../app/
        dest: /var/www/html/
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Remove default Apache web page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy website files
      copy:
        src: ../app/
        dest: /var/www/html/
        mode: '0644'
        owner: www-data
        group: www-data

    - name: Ensure correct permissions on /var/www/html
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: www-data
        group: www-data
        recurse: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
